FROM node:18

RUN apt-get update && apt-get install -y poppler-utils ghostscript


WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend ./

CMD ["node", "src/workers/conversion.worker.js"]
